config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { :scope => :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id]).destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @review = Review.new
  end

  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="border-bottom bg-white">
      <div class="container d-flex align-items-center justify-content-between py-2">
        <%= link_to lists_path do %>
        <h1><i class="fas fa-ticket-alt"></i> Movie Log</h1>
        <% end %>
        <%= link_to 'nueva lista?', new_list_path, class: 'btn btn-primary' %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1585951237313-1979e4df7385?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h3 id="banner-typed-text">Escribes tus listas y bookmarks!</h3>
  </div>
</div>

<div class="container">
  <div class="row mt-5">
    <div class="cards mb-5">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>
<%= link_to "nueva lista", new_list_path, class: "btn btn-primary" %>

<%
=begin%>
 <%= cl_image_tag @article.photo.key, height: 300, width: 400, crop: :fill %>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @article.photo.key, height: 300, crop: :fill %>')">
  Cool article
</div>
<%
=end%>

app/views/lists/new.html.erb
<div class="container">
  <h2>Crea tu lista!</h2>
  <div class="row justify-content-center mt-5">
    <div class="card p-3 mb-3 col-12 col-md-6 col-lg-6">
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'guardar lista', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>');">
  <div class="container">
    <h3><%= @list.name %>!</h3>
  </div>
</div>
<div class="container">
  <div class="mt-5">
    <div class="cards">
      <% @list.bookmarks.each do |bookmark| %>
      <div class="card-trip">
        <img src=<%= bookmark.movie.poster_url %>>
        <div class="card-trip-infos">
          <div>
            <h2><%= bookmark.movie.title %></h2>
            <p><%= bookmark.movie.overview %></p>
            <h2 class="mt-2">Bookmarks:</h2>
            <p><%= bookmark.comment %> <%= link_to "borrar", bookmark_path(bookmark), method: :delete, class: "btn btn-danger btn-sm ml-2" %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-start mt-5">
    <div class="card p-3 mb-3 col-12 col-md-6 col-lg-6">
      <h5 class="mt-5">Escribe nuevo bookmark...</h5>
      <%= simple_form_for([@list, @bookmark]) do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie, as: :radio_buttons %>
        <%= f.submit 'guardar bookmark', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
      <div class="mb-5">
        <h5 class="mt-5">Reviews</h5>
        <%= link_to "Escribir review", new_list_review_path(@list) %>
        <div class="card py-3 px-2">
          <ul>
          <% @list.reviews.each do |review| %>
            <li><%= review.content %></li>
          <% end %>
          </ul>
        </div>
      </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h2>Escribe tu review de la lista "<%= @list.name %>"</h2>
  <div class="row justify-content-center mt-5">
    <div class="card p-3 mb-3 col-12 col-md-6 col-lg-6">
      <%= simple_form_for([@list, @review]) do |f| %>
        <%= f.input :content %>
        <%= f.submit 'guardar review', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>